server:
  port: 8081

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001cloud.com:7001/eureka/
#设置服务器降级最大降级时间

#使用feign调用服务提供者，客户端消费服务降级配置
#feign:
#  hystrix:
#    enabled: true

#使用Ribbon+RestTemplate调用服务时，客户端消费服务降级的配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
