server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com/MissWangXN/springcloud-config.git #git仓库地址，存放公共配置
          #          uri: https://github.com/MissWangXN/springcloud-config.git #git仓库地址，存放公共配置
          ###搜索目录
          search-paths:
            - springcloud-config
          #            - /**
          username: 337018466@qq.com
          passphrase: xinao2015
        ####读取分支
      label: master

#服务注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
