server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置nacos地址

management:
  endpoints:
    web: #都暴露出来做监控
      exposure:
        include: '*'