server:
  port: 8081

spring:
  application:
     name: clous-consumer-order

###################################
cloud:
  consul:
    host: localhost
    port: 8500
    discovery:
      service-name: ${Spring.application.name}