server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes: #可配置多个路由，跨服务调用的接口都可以做路由
        - id: payment_routh    #payment_route #没有固定规则，但要求唯一，建议配合服务名
          #          uri: http://localhost:8001     #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址(采用eureka中的服务名动态匹配，带有负载均衡)
          predicates:
            - Path=/payment/get/**    #断言，请求中的路径相匹配的进行路由（**通配符，入参）

        - id: payment_routh2     #payment_route #没有固定规则，但要求唯一，建议配合服务名
          #          uri: http://localhost:8001     #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址(采用eureka中的服务名动态匹配，带有负载均衡)
          predicates: #predicate支持数组行形式，多个条件同时满足后才能路由转发
            - Path=/payment/lb/**     #断言，请求中的路径相匹配的进行路由
#            - After=2020-05-29T12:04:46.866+08:00[Asia/Shanghai] #在这个时间之后才能访问（不到时间会报错）
#            - Before=2020-06-29T13:04:46.866+08:00[Asia/Shanghai]
#            - Between=2020-05-29T12:04:46.866+08:00[Asia/Shanghai],2021-05-29T13:04:46.866+08:00[Asia/Shanghai]
#            - Cookie=username,wangxiaona  #cookie的k-v
#            - Header=X-Request-id,\d+  #请求头的k-v
#            - Host=**.atguigu.com
#            - Method=GET
#            - Query=username,\d+  #要有参数名username并且值还要是正数才能路由



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001cloud.com:7001/eureka
