server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment #服务名称

eureka:
  client:
    register-with-eureka: true    #将自己注册进eureka Server,默认为true
    fetch-registry: true     #从eureka Server抓取已有的注册信息，默认为true
    service-url:            #入住地址 = eureka Server的地址 = 物业公司
      defaultZone: http://eureka7001cloud.com:7001/eureka #单机版